import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { VerovioToolkit } from "verovio/esm";
import createVerovioModule from "verovio/wasm";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

async function generateSvg() {
  const meiPath = path.resolve(__dirname, "../test/fixtures/sample.mei");
  const svgPath = path.resolve(__dirname, "../test/fixtures/sample.svg");

  console.log(`Reading MEI from: ${meiPath}`);
  let meiContent: string;
  try {
    meiContent = await fs.readFile(meiPath, "utf-8");
  } catch (_e) {
    console.error(`Error: Could not read sample.mei at ${meiPath}`);
    process.exit(1);
  }

  console.log("Initializing Verovio...");
  // Verovio toolkit requires the WebAssembly module
  const VerovioModule = await createVerovioModule();
  const tk = new VerovioToolkit(VerovioModule);

  console.log("Setting options and loading data...");
  tk.setOptions({
    scale: 50,
    breaks: "auto",
    adjustPageHeight: true,
    adjustPageWidth: true,
  });

  tk.loadData(meiContent);

  console.log("Rendering SVG...");
  const rawSvg = tk.renderToSVG(1);
  const svg = `<!--\n  This file is automatically generated. Do not edit manually.\n  For how to generate this file, refer to the README.md in lib-verovio-react.\n-->\n${rawSvg}`;

  console.log(`Writing SVG to: ${svgPath}`);
  await fs.mkdir(path.dirname(svgPath), { recursive: true });
  await fs.writeFile(svgPath, svg, "utf-8");

  console.log("Done.");
}

generateSvg().catch((err) => {
  console.error("Failed to generate test fixture:", err);
  process.exit(1);
});
